<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByTitle($page, $nbPerPage)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT f 
                FROM AppBundle:Film f 
                ORDER BY f.titre ASC');

        $query
            // On définit l'annonce à partir de laquelle commencer la liste
            ->setFirstResult(($page-1) * $nbPerPage)
            // Ainsi que le nombre d'annonce à afficher sur une page
            ->setMaxResults($nbPerPage);
        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        
        return new Paginator($query, true);
    }
}
